# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEuropeanPutPrice <- function(nInt, Strike, Spot, Vol, Rfr, Expiry, Bar, nReps = 1000L) {
    .Call(`_GaworAleksandra_getEuropeanPutPrice`, nInt, Strike, Spot, Vol, Rfr, Expiry, Bar, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_GaworAleksandra_rcpp_hello_world`)
}

